insert into candidates (name, skills, years_experience, last_ctc_inr, current_location)
values
('Amit Verma', ARRAY['Python','Django','PostgreSQL'], 4, 1200000, 'Mumbai'),
('Sneha Iyer', ARRAY['React','Node.js','MongoDB'], 2, 800000, 'Bangalore'),
('Rahul Singh', ARRAY['Java','Spring Boot','MySQL'], 5, 1500000, 'Delhi'),
('Priya Nair', ARRAY['Python','FastAPI','AWS'], 3, 1100000, 'Kochi'),
('Arjun Mehta', ARRAY['Go','Kubernetes','Docker'], 6, 2200000, 'Pune'),
('Neha Kapoor', ARRAY['React','TypeScript','Next.js'], 4, 1400000, 'Gurgaon'),
('Rohit Sharma', ARRAY['Python','Flask','Redis'], 3, 1000000, 'Mumbai'),
('Karan Patel', ARRAY['Node.js','Express','MongoDB'], 5, 1600000, 'Ahmedabad'),
('Ananya Das', ARRAY['Python','Pandas','Data Analysis'], 2, 900000, 'Kolkata'),
('Vikram Joshi', ARRAY['Java','Kafka','Microservices'], 7, 2500000, 'Bangalore'),
('Sara Khan', ARRAY['Figma','UI/UX','Adobe XD'], 3, 950000, 'Delhi'),
('Manish Gupta', ARRAY['C++','Qt','Embedded Systems'], 6, 2000000, 'Noida'),
('Pooja Reddy', ARRAY['Python','TensorFlow','NLP'], 4, 1800000, 'Hyderabad'),
('Aditya Kulkarni', ARRAY['AWS','Terraform','DevOps'], 5, 1700000, 'Pune'),
('Simran Kaur', ARRAY['React Native','Mobile Dev','Firebase'], 3, 1200000, 'Chandigarh'),
('Nikhil Jain', ARRAY['PHP','Laravel','MySQL'], 4, 1100000, 'Jaipur'),
('Meera Menon', ARRAY['SQL','PowerBI','Data Analysis'], 2, 850000, 'Chennai'),
('Siddharth Roy', ARRAY['Python','Airflow','ETL'], 5, 1600000, 'Kolkata'),
('Harsh Vardhan', ARRAY['Vue.js','Firebase','JavaScript'], 3, 1050000, 'Delhi'),
('Deepak Yadav', ARRAY['Kotlin','Android','Jetpack'], 4, 1300000, 'Noida'),
('Ritika Sharma', ARRAY['Python','FastAPI','PostgreSQL'], 2, 950000, 'Mumbai'),
('Abhishek Mishra', ARRAY['Java','Spring Boot','Microservices'], 6, 2100000, 'Bangalore'),
('Kavya Nair', ARRAY['React','Redux','TypeScript'], 3, 1200000, 'Kochi'),
('Yash Shah', ARRAY['Node.js','Express','MongoDB'], 4, 1400000, 'Ahmedabad'),
('Tanvi Kulkarni', ARRAY['Python','Pandas','Machine Learning'], 2, 1000000, 'Pune'),
('Rakesh Kumar', ARRAY['C#','.NET','SQL Server'], 5, 1800000, 'Delhi'),
('Divya Iyer', ARRAY['Swift','iOS Development','UIKit'], 4, 1500000, 'Chennai'),
('Mohit Agarwal', ARRAY['DevOps','Docker','Kubernetes'], 6, 2300000, 'Gurgaon'),
('Shreya Banerjee', ARRAY['Figma','UI/UX','Design Systems'], 3, 1100000, 'Kolkata'),
('Ankit Tiwari', ARRAY['Python','Flask','MySQL'], 4, 1200000, 'Indore'),
('Pallavi Deshmukh', ARRAY['Java','Hibernate','Spring'], 5, 1700000, 'Nagpur'),
('Rohan Kapoor', ARRAY['React','Next.js','Tailwind'], 3, 1300000, 'Delhi'),
('Ayesha Siddiqui', ARRAY['Python','NLP','SpaCy'], 4, 1600000, 'Hyderabad'),
('Saurabh Jain', ARRAY['Node.js','NestJS','PostgreSQL'], 5, 1900000, 'Jaipur'),
('Nidhi Sharma', ARRAY['Data Analysis','Excel','SQL'], 2, 800000, 'Chandigarh'),
('Gaurav Singh', ARRAY['Go','Microservices','Docker'], 6, 2200000, 'Bangalore'),
('Ishita Gupta', ARRAY['React Native','Mobile Dev','Expo'], 3, 1250000, 'Noida'),
('Kunal Verma', ARRAY['AWS','Lambda','Serverless'], 5, 2000000, 'Mumbai'),
('Snehal Patil', ARRAY['Python','Django','REST APIs'], 4, 1400000, 'Pune'),
('Ravi Teja', ARRAY['Java','Kafka','Spring Boot'], 6, 2100000, 'Hyderabad'),
('Pritam Das', ARRAY['Vue.js','Nuxt.js','JavaScript'], 3, 1100000, 'Kolkata'),
('Aman Bansal', ARRAY['C++','Algorithms','System Design'], 5, 1800000, 'Delhi'),
('Komal Shah', ARRAY['UI/UX','Figma','Prototyping'], 2, 900000, 'Ahmedabad'),
('Shivam Yadav', ARRAY['Python','FastAPI','Redis'], 4, 1500000, 'Noida'),
('Anusha Reddy', ARRAY['Machine Learning','TensorFlow','Python'], 3, 1600000, 'Hyderabad'),
('Ritesh Gupta', ARRAY['PHP','Laravel','REST APIs'], 5, 1700000, 'Jaipur'),
('Pankaj Kumar', ARRAY['DevOps','CI/CD','Jenkins'], 6, 2000000, 'Gurgaon'),
('Sonal Mehta', ARRAY['React','TypeScript','Redux'], 3, 1300000, 'Mumbai'),
('Varun Khanna', ARRAY['Java','Spring','MySQL'], 5, 1800000, 'Delhi'),
('Deepa Nair', ARRAY['Data Science','Python','Pandas'], 4, 1700000, 'Kochi'),
('Tarun Sharma', ARRAY['Node.js','Express','MongoDB'], 3, 1200000, 'Chandigarh'),
('Aditi Singh', ARRAY['Figma','UI/UX','Design Thinking'], 2, 950000, 'Delhi'),
('Naveen Kumar', ARRAY['C','Embedded','RTOS'], 7, 2300000, 'Bangalore'),
('Rashmi Kulkarni', ARRAY['Python','Flask','SQLAlchemy'], 4, 1400000, 'Pune'),
('Hemant Verma', ARRAY['Go','Kubernetes','gRPC'], 6, 2400000, 'Noida'),
('Neeraj Patel', ARRAY['Node.js','GraphQL','Apollo'], 5, 1900000, 'Ahmedabad'),
('Bhavna Iyer', ARRAY['Swift','iOS','CoreData'], 4, 1500000, 'Chennai'),
('Arpit Jain', ARRAY['Java','Spring Boot','Microservices'], 6, 2200000, 'Jaipur'),
('Sakshi Gupta', ARRAY['React Native','Expo','Mobile Dev'], 3, 1200000, 'Delhi'),
('Manoj Singh', ARRAY['Python','ETL','Airflow'], 5, 1800000, 'Kolkata'),
('Alok Mishra', ARRAY['C#','.NET','Azure'], 6, 2100000, 'Noida'),
('Riya Sharma', ARRAY['UI/UX','Figma','Adobe XD'], 2, 900000, 'Mumbai'),
('Nitin Agarwal', ARRAY['DevOps','Docker','AWS'], 5, 2000000, 'Gurgaon'),
('Jyoti Verma', ARRAY['Python','Machine Learning','Scikit-learn'], 3, 1500000, 'Indore'),
('Sandeep Yadav', ARRAY['JavaScript','React','Next.js'], 4, 1400000, 'Delhi'),
('Ashutosh Pandey', ARRAY['Java','Spring','Hibernate'], 5, 1800000, 'Varanasi'),
('Preeti Singh', ARRAY['Data Analysis','SQL','PowerBI'], 2, 850000, 'Lucknow'),
('Vikas Sharma', ARRAY['Node.js','NestJS','MongoDB'], 4, 1500000, 'Chandigarh'),
('Rekha Nair', ARRAY['Python','Django','REST APIs'], 3, 1300000, 'Kochi'),
('Anil Kumar', ARRAY['C++','STL','Algorithms'], 6, 2000000, 'Bangalore'),
('Swati Joshi', ARRAY['React','Redux','JavaScript'], 3, 1200000, 'Pune'),
('Harish Gupta', ARRAY['Go','Docker','Microservices'], 5, 1900000, 'Delhi'),
('Mehul Shah', ARRAY['Node.js','Express','MySQL'], 4, 1400000, 'Ahmedabad'),
('Isha Kapoor', ARRAY['Figma','UI/UX','Prototyping'], 2, 950000, 'Gurgaon'),
('Rajeev Singh', ARRAY['Java','Kafka','Spring Boot'], 7, 2500000, 'Noida'),
('Piyush Jain', ARRAY['Python','Flask','PostgreSQL'], 4, 1500000, 'Jaipur'),
('Kritika Mehta', ARRAY['React Native','Mobile Dev','Firebase'], 3, 1200000, 'Mumbai'),
('Vivek Tiwari', ARRAY['DevOps','CI/CD','AWS'], 6, 2100000, 'Bangalore'),
('Shalini Reddy', ARRAY['Machine Learning','TensorFlow','Python'], 4, 1800000, 'Hyderabad'),
('Girish Nair', ARRAY['C','Embedded Systems','RTOS'], 7, 2300000, 'Chennai'),
('Rahul Khanna', ARRAY['Node.js','GraphQL','Apollo'], 5, 1900000, 'Delhi'),
('Ankit Sharma', ARRAY['JavaScript','Vue.js','Nuxt.js'], 3, 1200000, 'Noida');